development:
  adapter: mysql2
  encoding: utf8
  pool: 5
  host: 1.1.1.1
  username: user
  password: password
  database: continuous_development

test:
  adapter: mysql2
  encoding: utf8
  pool: 5
  host: 1.1.1.1
  username: user
  password: password
  database: continuous_test

production:
  adapter: mysql2
  encoding: utf8
  pool: 5
  host: 1.1.1.1
  database: continuous_production
  username: user
  password: password

