# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2ba417a68e6ae840d44a7e3128ecd82a72761241ea8e74928b6c824a2b9077b544d419073d8c23fe819e9bafa2aec18b6a554719682f72b02e1dae765bd8648b

test:
  secret_key_base: 93bdba06d8f3e54fcfe14b4bed984b1fabb4880cd8397a10d39224f21dff636f3f359efc3799ee2f8b317c124326803b9431eae752c17491c3f690d9bbc5bbf7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: xxxxyyyyzzzzz 
